quarkus:
  log:
    level: INFO
  http:
    port: 8790
    cors:
      ~: true
      origins: http://localhost:5173, http://localhost:5174,  https://4e19-2a09-bac5-3a24-18d2-00-279-87.ngrok-free.app
      headers: accept, authorization, content-type, x-requested-with
      methods: GET, OPTIONS, POST, DELETE, PUT, PATCH
  datasource:
    db-kind: mysql
    username: root
    password: ""
    jdbc:
      url: jdbc:mysql://localhost:3306/absensi_ukk
  hibernate-orm:
    database:
      generation:
        ~: none